export const CARDS_IN_LESSON = "cardsInLesson";

export enum EActionType {
  GET_DECK_REQUEST = "GET_DECK_REQUEST",
  GET_DECK_SUCCESS = "GET_DECK_SUCCESS",
  GET_DECK_FAILURE = "GET_DECK_FAILURE",
  GET_DECK_LIST_REQUEST = "GET_DECK_LIST_REQUEST",
  GET_DECK_LIST_SUCCESS = "GET_DECK_LIST_SUCCESS",
  GET_DECK_LIST_FAILURE = "GET_DECK_LIST_FAILURE",
  ADD_DECK = "ADD_DECK",
  PUT_DECK = "PUT_DECK",
  UPDATE_DECK = "UPDATE_DECK",
  ADD_CARD = "ADD_CARD",
  UPDATE_CARD = "UPDATE_CARD",
  DELETE_CARD = "DELETE_CARD",
  DELETE_DECK = "DELETE_DECK",
}
